# Generated by Django 5.0.6 on 2026-05-27 16:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DAG',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('schedule', models.CharField(blank=True, help_text='Cron expression e.g. "0 9 * * *" for daily at 9am', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(choices=[('DUMMY', 'Dummy (simulated)'), ('PYTHON', 'Python Function'), ('HTTP', 'HTTP Request')], default='DUMMY', max_length=20)),
                ('task_config', models.JSONField(blank=True, default=dict, help_text='Config depends on task_type. DUMMY: {"duration": 3}, PYTHON: {"code": "..."}, HTTP: {"url": "...", "method": "GET"}')),
                ('max_retries', models.PositiveIntegerField(default=1)),
                ('retry_delay_seconds', models.PositiveIntegerField(default=5)),
                ('timeout_seconds', models.PositiveIntegerField(default=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='dags.dag')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('dag', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='dags.task')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='dags.task')),
            ],
            options={
                'unique_together': {('task', 'depends_on')},
            },
        ),
    ]
